apiVersion: dsdf.7sg.ai/v1
kind: DataSourceDefinition
metadata:
  name: llm-endpoint-crusoe
  version: "1.0.0"
  tags:
    env: prod
home:
  tdfRef: crusoe
auth:
  method: apikey
  secretRefs:
  - crusoe-openai-api-key
secrets:
  provider: inherit
  inheritFromWdf: true
  secretRefs: []
